apiVersion: v2
name: velero-sierra-group
description: Wrapper chart for velero
type: application
version: 0.1.0

dependencies:
  - name: velero
    version: "10.0.9"  # Especifica la versión del chart de velero que deseas usar
    repository: "https://vmware-tanzu.github.io/helm-charts"  # URL del repositorio de velero
